@extends('layouts.app')
@section('content')
<div class="max-w-5xl mx-auto px-4 py-8"><h1 class="text-3xl font-bold">Paiement de {{ $order->order_number }}</h1><p class="text-gray-600 mt-2">Le panier est unique, mais le paiement est séparé automatiquement par vendeur.</p>
@if(session('success'))<div class="mt-4 p-3 rounded bg-green-100 text-green-800">{{session('success')}}</div>@endif
@foreach($groups as $id=>$g)<div class="mt-7 bg-white border rounded-2xl p-6"><div class="flex justify-between"><div><h2 class="text-xl font-bold">Vendeur : {{$g['vendor']->name}}</h2><div class="text-sm text-gray-500">Sous-commande : {{$g['vendorOrder']->order_number}}</div></div><div class="text-2xl font-extrabold">{{number_format($g['total'],0,',',' ')}} FCFA</div></div>
<div class="mt-4 space-y-2">@foreach($g['vendorOrder']->items as $item)<div class="flex justify-between border-b py-2"><span>{{$item->product_name}} × {{$item->quantity}}</span><b>{{number_format($item->total,0,',',' ')}} FCFA</b></div>@endforeach</div>
<div class="grid md:grid-cols-2 gap-4 mt-5">@forelse($g['methods'] as $m)<div class="border rounded-xl p-4"><div class="font-semibold">{{$m->label()}}</div><div>Nom : <strong>{{$m->account_name}}</strong></div><div>Numéro de transfert : <strong>{{$m->transfer_number}}</strong></div></div>@empty<div class="bg-yellow-50 text-yellow-800 p-4 rounded-xl">Ce vendeur n'a pas configuré de numéro de transfert.</div>@endforelse</div>
@php $approved=App\Models\ManualPaymentSubmission::where('vendor_order_id',$g['vendorOrder']->id)->where('status','approved')->exists(); $pending=App\Models\ManualPaymentSubmission::where('vendor_order_id',$g['vendorOrder']->id)->where('status','pending')->exists(); @endphp
@if($approved)<div class="mt-5 p-3 rounded-xl bg-green-100 text-green-800">Paiement de ce vendeur validé par l'administrateur.</div>@elseif($pending)<div class="mt-5 p-3 rounded-xl bg-yellow-100 text-yellow-800">Preuve envoyée. En attente de validation.</div>@else
<form method="POST" action="{{route('order.payment.submit',$order)}}" enctype="multipart/form-data" class="mt-5 space-y-4 border-t pt-5">@csrf<input type="hidden" name="vendor_order_id" value="{{$g['vendorOrder']->id}}"><select name="provider" required class="w-full border rounded-xl p-3"><option value="">Choisir le moyen de paiement</option>@foreach($g['methods'] as $m)<option value="{{$m->provider}}">{{$m->label()}} — {{$m->transfer_number}}</option>@endforeach</select><input name="payer_name" required value="{{auth()->user()->name}}" placeholder="Nom du payeur" class="w-full border rounded-xl p-3"><input name="transaction_reference" placeholder="Référence/ID de transaction (facultatif)" class="w-full border rounded-xl p-3"><input type="file" name="screenshot" accept="image/*" required class="w-full border rounded-xl p-3"><button class="bg-slate-950 text-white rounded-xl px-6 py-3 font-semibold">Envoyer la preuve</button></form>@endif</div>@endforeach
<div class="mt-7 text-right text-2xl font-extrabold">Total global : {{number_format($order->total,0,',',' ')}} FCFA</div></div>@endsection
